# Generated by Django 5.0.7 on 2024-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dclinic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="professionals",
            field=models.ManyToManyField(related_name="services", to="dclinic.doctor"),
        ),
    ]
