# Generated by Django 5.0.7 on 2024-10-05 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dclinic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.AddField(
            model_name="appointment",
            name="ending_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="starting_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterUniqueTogether(
            name="professionalavailability",
            unique_together={("professional", "date", "start_time", "end_time")},
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid")],
                        max_length=50,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="dclinic.appointment",
                    ),
                ),
            ],
        ),
    ]
