# Generated by Django 5.0.7 on 2024-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dclinic", "0002_remove_appointment_time_appointment_ending_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auser",
            name="tg_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="auser",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
