# Generated by Django 5.0.7 on 2024-08-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dclinic", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dclinic.category",
            ),
            preserve_default=False,
        ),
    ]
