# Generated by Django 5.0.7 on 2024-10-13 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dclinic", "0003_auser_tg_id_alter_auser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="auser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="auser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
