# Generated by Django 5.0.7 on 2024-10-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dclinic", "0004_auser_created_at_auser_is_active_auser_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="auser",
            name="passport_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
