# Generated by Django 5.0.7 on 2024-08-04 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dclinic", "0004_service_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
